#!/usr/bin/env bash

if [[ -s "/home/action/.rvm/environments/ruby-2.0.0-p247@learn-rails" ]]
then
  source "/home/action/.rvm/environments/ruby-2.0.0-p247@learn-rails"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/environments/ruby-2.0.0-p247@learn-rails'" >&2
  exit 1
fi
